<a href="https://colab.research.google.com/github/Suriya6744/BasicProg_DataViz65/blob/main/Recap_4_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Matrix Slicing

In [ ]:
import numpy

In [ ]:
list_a = [[2,4,5],[1,2,3],[9,8,7],[3,6,9]]
mat_a = numpy.array(list_a)
mat_a

array([[2, 4, 5],
       [1, 2, 3],
       [9, 8, 7],
       [3, 6, 9]])

In [ ]:
import numpy as np

In [ ]:
list_b = [[-1,-1,2,4,5],[-2,-2,1,2,3],[-3,-3,9,8,7],[-4,-4,3,6,9]]
mat_b = np.array(list_b)
mat_b

array([[-1, -1,  2,  4,  5],
       [-2, -2,  1,  2,  3],
       [-3, -3,  9,  8,  7],
       [-4, -4,  3,  6,  9]])

## Quiz2

1. slice ค่าลบออกมาจาก ```mat_b```
2. slice ```[1,2,3]``` จาก ```mat_a```
3. slice ```[[1,3],[9,7],[3,9]]``` ออกมาจาก ```mat_b```

In [ ]:
#ข้อ 1
mat_b[:4,:2] 

array([[-1, -1],
       [-2, -2],
       [-3, -3],
       [-4, -4]])

In [ ]:
#ข้อ 2
mat_a[1]

array([1, 2, 3])

In [ ]:
#ข้อ 3
mat_b[1:4:, 2:5:2]

array([[1, 3],
       [9, 7],
       [3, 9]])

# Quiz3

เขียน function แสดงความต่างของเวลาโดย input อยู่ในรูปแบบ 'XX:YY:ZZ - AA:BB:CC'

และวนลูปแสดงผลของ input ต่อไปนี้

* '09:11:50 - 12:30:15'
* '13:41:07 - 20:00:18'
* '00:00:00 - 23:59:59'
* '18:04:11 - 00:00:00'
* '21:30:00 - 03:05:15'

ตัวอย่าง input ```'00:00:00-01:00:00'```

output ```ช่วงระยะเวลาระหว่าง 00:00:00 ถึง 01:00:00 มีเวลาทั้งหมด 3,600 วินาที```

In [1]:
time = '09:11:50 - 12:30:15'
time

'09:11:50 - 12:30:15'

In [2]:
t = time
t

'09:11:50 - 12:30:15'

In [3]:
input_split = t.split(' - ')
input_split

['09:11:50', '12:30:15']

In [4]:
starttimeSP = input_split[0].split(':')
endtimeSP = input_split[-1].split(':')
print(starttimeSP,endtimeSP,sep='\n')

['09', '11', '50']
['12', '30', '15']


In [5]:
def calculate_time(time):
    t = time
    input_split = t.split('-')
    starttimeSP = input_split[0].split(':')
    endtimeSP = input_split[1].split(':')

    starttime = 3600*int(starttimeSP[0])+60*int(starttimeSP[1])+int(starttimeSP[2])
    endtime = 3600*int(endtimeSP[0])+60*int(endtimeSP[1])+int(endtimeSP[2])

    if endtime > starttime :
        print(f'ระยะเวลาระหว่าง {input_split[0]} และ {input_split[1]} ห่างกันเท่ากับ {endtime-starttime:,} วินาที')
    else:
        print(f'ระยะเวลาระหว่าง {input_split[0]} และ {input_split[1]} ห่างกันเท่ากับ {endtime+24*60*60 - starttime: ,} วินาที')

In [6]:
for time in ['09:11:50 - 12:30:15','13:41:07 - 20:00:18','00:00:00 - 23:59:59','18:04:11 - 00:00:00','21:30:00 - 03:05:15']:
    T = time
    calculate_time(T)

ระยะเวลาระหว่าง 09:11:50  และ  12:30:15 ห่างกันเท่ากับ 11,905 วินาที
ระยะเวลาระหว่าง 13:41:07  และ  20:00:18 ห่างกันเท่ากับ 22,751 วินาที
ระยะเวลาระหว่าง 00:00:00  และ  23:59:59 ห่างกันเท่ากับ 86,399 วินาที
ระยะเวลาระหว่าง 18:04:11  และ  00:00:00 ห่างกันเท่ากับ  21,349 วินาที
ระยะเวลาระหว่าง 21:30:00  และ  03:05:15 ห่างกันเท่ากับ  20,115 วินาที
