<a href="https://colab.research.google.com/github/Suriya6744/BasicProg_DataViz65/blob/main/Recap_4_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Matrix Slicing

In [ ]:
import numpy

In [ ]:
list_a = [[2,4,5],[1,2,3],[9,8,7],[3,6,9]]
mat_a = numpy.array(list_a)
mat_a

array([[2, 4, 5],
       [1, 2, 3],
       [9, 8, 7],
       [3, 6, 9]])

In [ ]:
import numpy as np

In [ ]:
list_b = [[-1,-1,2,4,5],[-2,-2,1,2,3],[-3,-3,9,8,7],[-4,-4,3,6,9]]
mat_b = np.array(list_b)
mat_b

array([[-1, -1,  2,  4,  5],
       [-2, -2,  1,  2,  3],
       [-3, -3,  9,  8,  7],
       [-4, -4,  3,  6,  9]])

## Quiz2

1. slice ค่าลบออกมาจาก ```mat_b```
2. slice ```[1,2,3]``` จาก ```mat_a```
3. slice ```[[1,3],[9,7],[3,9]]``` ออกมาจาก ```mat_b```

In [ ]:
#ข้อ 1
mat_b[:4,:2] 

array([[-1, -1],
       [-2, -2],
       [-3, -3],
       [-4, -4]])

In [ ]:
#ข้อ 2
mat_a[1]

array([1, 2, 3])

In [ ]:
#ข้อ 3
mat_b[1:4:, 2:5:2]

array([[1, 3],
       [9, 7],
       [3, 9]])

# Quiz3

เขียน function แสดงความต่างของเวลาโดย input อยู่ในรูปแบบ 'XX:YY:ZZ - AA:BB:CC'

และวนลูปแสดงผลของ input ต่อไปนี้

* '09:11:50 - 12:30:15'
* '13:41:07 - 20:00:18'
* '00:00:00 - 23:59:59'
* '18:04:11 - 00:00:00'
* '21:30:00 - 03:05:15'

ตัวอย่าง input ```'00:00:00-01:00:00'```

output ```ช่วงระยะเวลาระหว่าง 00:00:00 ถึง 01:00:00 มีเวลาทั้งหมด 3,600 วินาที```

In [36]:
dict_A = {1:'09:11:50 - 12:30:15',2:'13:41:07 - 20:00:18',3:'00:00:00 - 23:59:59',4:'18:04:11 - 00:00:00',5:'21:30:00 - 03:05:15'}
dict_A

{1: '09:11:50 - 12:30:15',
 2: '13:41:07 - 20:00:18',
 3: '00:00:00 - 23:59:59',
 4: '18:04:11 - 00:00:00',
 5: '21:30:00 - 03:05:15'}

In [49]:
input_split =dict_A[1].split('-'),dict_A[2].split('-'),dict_A[3].split('-'),dict_A[4].split('-'),dict_A[5].split('-')
input_split
input_split.pop()
input_split

AttributeError: ignored

In [33]:
gg = input_split[0].split(':')
gg


AttributeError: ignored

In [15]:
for each in input:
  def calculate_time(input):
    input_split = input.split(' - ')
    starttimeSP = input_split[0].split(':')
    endtimeSP = input_split[-1].split(':')

    starttime = 3600*int(starttimeSP[0]) + 60*int(starttimeSP[1]) + int(starttimeSP[2])
    endtime = 3600*int(endtimeSP[0]) + 60*int(endtimeSP[1]) + int(endtimeSP[2])

    print(f'ระยะเวลาระหว่าง {input_split[0]} และ {input_split[1]} ห่างกันเท่ากับ {endtime-starttime:,} วินาที')
    print('----------------')